### ISSUE TITLE
Implementar e testar a classe VisitorEntityObjectImpl.

### ISSUE THREAD

**Issue by proffbgoncalves** [proffbgoncalves/portal_eclb#46]
## Objetivo

Implementar e testar a classe VisitorEntityObjectImpl.

### Tarefas

- [x] Criar a interface Visitor;
- [x] Implementar a classe concreta VisitorDTO;
- [x] Implementar testes de unidade para a classe VisitorDTO;
- [x] Criar a interface VisitorEntityObject;
- [x] Criar a interface VisitorDAO;
- [x] Modificar a interface DAOFactory;
- [x] Criar, implementar e testar a classe VisitorEntityObjectImpl.

### Ferramentas

- Framework de testes do Flutter;
- Pacote mockito versão >= 5.4.4;
- Pacote build_runner >=  2.4.11;

### Documentação

- Mockito: https://pub.dev/packages/mockito

**Comment by matheusbor** [comment]
Oi fabrício, estava registrando VisitorDAO em DAOFactory e houve um erro em `lib/resource/dao/mariadb/mariadb_dao_factory.dart`

Acredito que seja mais uma tarefa a colocar nas issues, 
//Este método é responsável por instanciar a classe MariaDBVisitorDAO.
`@override
  VisitorDAO createVisitorDAO(DatabaseSessionManager databaseSessionManager) {
    // TODO: implement createVisitorDAO
    throw UnimplementedError();
  }`
